### ISSUE TITLE
Marco Legal

### ISSUE THREAD

**Issue by jrborbars** [matehackers/99problems#10]
Verificar o "marco legal" para a criaćão do hackerspace/associaćão/igreja/whatever. Ligado à issue #9 .
Portado da planilha https://docs.google.com/spreadsheets/d/1VcajDXiXycHjTBfZ69YCaOSTw9_g_F0EV4eQQB6Kk0A/edit#gid=1.

**Comment by hoarf** [comment]
duplicado com a issue, fechando porque <razões>

**Comment by hoarf** [comment]
duplicado com a issue, fechando porque [razões]
