### ISSUE TITLE
Aproximaćão com outras entidades/grupos

### ISSUE THREAD

**Issue by jrborbars** [matehackers/99problems#11]
Aproximar o hackerspace com outros grupos, como outros hackerspaces, universidades, etc.
Portado da planilha https://docs.google.com/spreadsheets/d/1VcajDXiXycHjTBfZ69YCaOSTw9_g_F0EV4eQQB6Kk0A/edit#gid=1.

**Comment by hoarf** [comment]
fechado por ser open ended demais...

**Comment by jrborbars** [comment]
Aproveita e apaga a planilha do Docs também......
