### ISSUE TITLE
Planejar eventos no hackerspace

### ISSUE THREAD

**Issue by jrborbars** [matehackers/99problems#12]
Planejar eventos no hackerspace, como dia do arduino, dia do raspberry pi, dia da música (eletrônica ou não), etc. 
Portado da planilha https://docs.google.com/spreadsheets/d/1VcajDXiXycHjTBfZ69YCaOSTw9_g_F0EV4eQQB6Kk0A/edit#gid=1.

**Comment by hoarf** [comment]
fechando esse aqui porque eu posso

**Comment by hoarf** [comment]
fechando esse aqui porque eu posso

**Comment by jrborbars** [comment]
Fez um evento? Ou já planejou?
Este tópico é para discutir quais eventos podem ser feitos para utilizar o espaco. Por isso foi portado da planilha do Drive.

**Comment by hoarf** [comment]
eu acho que a gente deve limitar as issues a coisas que podem potencialmente sofrer uma ação imediata... discussões e reflexões melhor deixar pra lista de e-mails ou pro telegram

**Comment by jrborbars** [comment]
A planilha é de quando? E ainda não foi resolvido este problema........

Em 29 de abril de 2015 14:05, Alan notifications@github.com escreveu:

> eu acho que a gente deve limitar as issues a coisas que podem
> potencialmente sofrer uma ação imediata... discussões e reflexões melhor
> deixar pra lista de e-mails ou pro telegram
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matehackers/99problems/issues/12#issuecomment-97505652
> .

## 

José Ricardo Borba

**Comment by hoarf** [comment]
sugiro quebrar isso em varias issues então.. é meio difícil resolver o planejamento do etc

**Comment by jrborbars** [comment]
Tu é muito pragmático. Deixa o povo "botar para fora" e dizer o que quiser
nesta issue. Qual evento? Bora fazer acontecer.....

2015-04-29 14:43 GMT-03:00 Alan notifications@github.com:

> sugiro quebrar isso em varias issues então.. é meio difícil resolver o
> planejamento do etc
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matehackers/99problems/issues/12#issuecomment-97515566
> .

## 

José Ricardo Borba

**Comment by hoarf** [comment]
pragmatico IDTIMWYTIM

**Comment by jrborbars** [comment]
Pragmatico WTFWY

2015-04-29 14:50 GMT-03:00 Alan notifications@github.com:

> pragmatico IDTIMWYTIM
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matehackers/99problems/issues/12#issuecomment-97517121
> .

## 

José Ricardo Borba

**Comment by lfzawacki** [comment]
Vou fechar. Fechei.
