### ISSUE TITLE
Identidade visual do site do Mate

### ISSUE THREAD

**Issue by jrborbars** [matehackers/99problems#14]
Lembrei que a Morvana estava trabalhando no site. Levantado pelo Joel, Alan e Pansera que poderia ser do Mate. Tá aí. Foi dada a largadada.

**Comment by morvanabonin** [comment]
Eu criei uma conta no trello https://trello.com/b/1YBX2oOv/site-landing-page e implementei uma parte e mudei de ideia depois :P 
Mas não implementei a ideia, tah no meu backlog, mas se o pessoal quiser continuar como o Eduardo está interessado, acho legal, a ideia que tive é fazer um menu lateral como o de uma wiki só que mais organizado (esses dias eu passei a wiki e não achei o endereço que era o que o cara queria). Acho que um layout deveria enfocar coisas que hoje são bastante pertinentes ao Matehackers e mostrem a cara dele.

**Comment by eduardoferras** [comment]
Conversei com a Morvana sobre o desenvolvimento do site e chegamos a uma ideia bem bacana.

Estou agora formulando ela certinho, para iniciar o desenvolvimento e compartilhar com o pesssoal como está ficando.

**Comment by cmdalbem** [comment]
Oi pessoal. Precisando uma ajuda pra fazer o front-end, ou mesmo uma mão à mais no back, eu adoraria ajudar.

**Comment by lfzawacki** [comment]
Como anda essa issue?

**Comment by iuriguilherme** [comment]
Requisitando relatório acerca do fechamento do problema @lfzawacki

**Comment by lfzawacki** [comment]
Fechado por abandono.
