### ISSUE TITLE
Como registrar um evento no Mate eventos?

### ISSUE THREAD

**Issue by jrborbars** [matehackers/99problems#16]
Esse eu ainda não sei. Guilherme, diz aí?

**Comment by lfzawacki** [comment]
EDIT: Agora entendi que você quer um guia melhorzinho. Vamos botando eles aqui https://matehackers.org/suporte_cursos_matehackers

MENSAGEM ORIGINAL: Cria uma conta e registra, depois tem que ser aprovado por um admin (no momento eu e o guilherme), mas não tem misterio.

**Comment by hoarf** [comment]
isso é uma issue?

**Comment by jrborbars** [comment]
@hoarf Achei que isto fosse para qualquer "ser" do Matehackers usar, e não achei instrucões (nem informacão) para tal. Por isso a "issue".
