### ISSUE TITLE
Achar a minha extensão elétrica

### ISSUE THREAD

**Issue by iuriguilherme** [matehackers/99problems#19]
Deixei uma extensão padrão novo de 1,8m com três saídas, e também um adaptador elétrico.

Emprestei pra alguém em um daqueles eventos de hipsters que tem de vez em quando no prédio.

Contanto que esteja dentro do hackerspace, ta ótimo.

**Comment by lfzawacki** [comment]
Já achou? Posso fechar?

**Comment by iuriguilherme** [comment]
Não é mais minha, é do movimento.
