### ISSUE TITLE
Migrar do unlock para o apoia.se

### ISSUE THREAD

**Issue by lfzawacki** [matehackers/99problems#23]
Inspirado por https://unlock.fund/pt-BR/raulhc . Vou começar tentando fazer algo parecido com a página inicial da nossa wiki

**Comment by guest42c** [comment]
ótimo, em qual página faremos isso? tava pensando em fazer isso também....

**Comment by lfzawacki** [comment]
https://matehackers.org/campanha_unlock

**Comment by lfzawacki** [comment]
https://unlock.fund/pt-BR/matehackers coloquei umas coisas novas la

**Comment by morvanabonin** [comment]
Em uma conversa, chegamos a conclusão que, a página do Unlock dever ser melhorada não só na questão do visual, mas do conteúdo, mas apelativo e referenciando a pessoa que está lendo em uma chamada, envolvendo-a. Além de mostrar coisas que já foram feitas e o que é o espaço.

**Comment by guest42c** [comment]
A frase "Quer ver a gente sendo mal representado em mídias tradicionais?" pega muito mal. Sem entrar no mérito da válidade da frase, ela pode ser facilmente mal interpretada.

No mais concordo com o que a morvana colocou.
Segue link com minhas fotos dos eventos do mate:  https://www.dropbox.com/sh/izkf1zukmqxy18x/AADnTUSZseFq_1I529JIcFQra?dl=0

Um video me parece o ideal pra se ter logo no inicio. E também listar algumas metas mais "ousadas" para comprar equipamentos pra um fablab por exemplo.

**Comment by morvanabonin** [comment]
Acho bem legal a ideia do vídeo @guilhermeka. O @JGrigolo já está cuidando em parte de melhorar a página, a criação de um novo logo foi, também, pensando no Unlock e o texto ele tinha uma ideia. Dá para ajudar dando ideias e juntos contruir algo bem bacana :)

**Comment by guest42c** [comment]
O Garoa ta começando a fazer isso tambem:
https://www.youtube.com/watch?v=RT8jQ3V4-aY
https://unlock.fund/pt-BR/garoa

**Comment by lfzawacki** [comment]
Troquei o título porque já está na hora de migrarmos para outra plataforma, os devs do unlock já entraram em contato comigo há algum tempo para dizer que ele não é mais desenvolvido e talvez seja a hora de migrar para o https://apoia.se que tá mais hype agora no momento.

**Comment by lfzawacki** [comment]
It was done
