### ISSUE TITLE
requisitar a rede bifásica pro hackerspace junto a companhia elétrica (popular não tem 220v)

### ISSUE THREAD

**Issue by hoarf** [matehackers/99problems#25]
/pipoca (denied!)

**Comment by iuriguilherme** [comment]
Eu li sobre o assunto e é só emendar dois fios que estão dando 110V de tensão. O resultado é que na ponta deve chegar 220V de tensão e consequentemente diminuir a amperagem.

**Comment by iuriguilherme** [comment]
Requisitando relatório acerca do fechamento o problema @lfzawacki

**Comment by lfzawacki** [comment]
Fechado por abandono.
