### ISSUE TITLE
Cabo de rede indisponível

### ISSUE THREAD

**Issue by rsip22** [matehackers/99problems#28]
O cabo de rede que passa de uma sala para a outra está sem a ponteira e não funciona. Isso precisa ser consertado para que computadores e dispositivos sem wi-fi possam se conectar. No mundo ideal, um hub ou roteador já ficaria na ponta desse cabo prontinho só para conectar.

**Comment by iuriguilherme** [comment]
Eu tenho a ferramenta pra apertar as pontas do cabo e o conhecimento pra saber em que **ordem** no **jeito certo** os fios têm que estar. Sem **ordem** e **jeito certo** não funciona.

**Comment by relsi** [comment]
Cabo de rede arrumado pelos meninos da rede.

**Comment by iuriguilherme** [comment]
Testei aqui e ta do jeito certo e na ordem.
