### ISSUE TITLE
revisar os computadores da abrace e descobrir quais não estão funcionando

### ISSUE THREAD

**Issue by hoarf** [matehackers/99problems#4]
e atualizar a planilha https://docs.google.com/spreadsheets/d/1T6m0DyEA8z1YQ-lnzR1ws2-VXaB3EN_qWTm1n3B4qQQ/edit?usp=drive_web

**Comment by relsi** [comment]
Terminei a revisão dos Desktops Dell. Todos com Xubuntu 14.04 instalado. Tem que identificar as características agora, memória, processador, etc.

Os desktops sem numeração identifiquei como SIXXX. Restam 3 desses para verificar, mas pelas características serão descartados. 

As máquinas que foram colocadas para canibalizar realizei testes trocando memórias e HD; as fontes funcionam; as memórias e HDs foram colocadas em outras máquinas que estavam sem, ou foram guardadas na segunda porta do ármario.

Convém substituir o gabinete da máquina 156. 

Várias máquinas não foram localizadas, quem souber que destino tiveram, favor anotar na planilha.

**Comment by lfzawacki** [comment]
Fechando.
