### ISSUE TITLE
desmontar os video cassetes antigos e remover os motores

### ISSUE THREAD

**Issue by hoarf** [matehackers/99problems#5]

**Comment by desireesantos** [comment]
Pode deixar comigo !

**Comment by felipesanches** [comment]
Se houver displays VFD e chips de EPROM, eu tenho interesse também. Preferencialmente com uma foto da placa mãe antes da remoção dos chips.

PS: Estarei no FISL fazendo oficina de emulação e engenharia reversa de dispositivos digitais.
