### ISSUE TITLE
instalar uma campainha no mate

### ISSUE THREAD

**Issue by hoarf** [matehackers/99problems#7]

**Comment by guest42c** [comment]
Vou doar outra campainha. Já to com ela, logo levo pro mate.

**Comment by hoarf** [comment]
o guilherme doou a campainha mas ela usa pilhas tamanho a23 que não tem no mate.. alguem tem umas de bobera ae?

https://encrypted.google.com/search?q=a23&safe=off&hl=pt&source=lnms&tbm=isch&sa=X&ei=Yak7Ve3RDcbHsQShhoCADg&ved=0CAkQ_AUoAw&biw=1364&bih=684#safe=off&hl=pt&tbm=isch&q=a23+battery

**Comment by hoarf** [comment]
foi trazido uma pilha pela morvana hoje a tarde

**Comment by hoarf** [comment]
a campainha ja esta funcionando. mas devido ao pessoal de fora do mate estar usando talvez so seja colocada no sábado
