### ISSUE TITLE
Estatuto

### ISSUE THREAD

**Issue by jrborbars** [matehackers/99problems#9]
Escrever o estatuto do hackerspace/igreja/associaćão/whatever.
Portado da planilha https://docs.google.com/spreadsheets/d/1VcajDXiXycHjTBfZ69YCaOSTw9_g_F0EV4eQQB6Kk0A/edit#gid=1.

**Comment by hoarf** [comment]
isso é o que temos até agora https://github.com/matehackers/estatutomate

**Comment by jrborbars** [comment]
Conversei com a Carolina do CCDPOA esta semana e ela tem ótimas contribuicões para dar. Ela já tem um trabalho neste sentido e pode nos ajudar.

**Comment by iuriguilherme** [comment]
Só pra registrar que eu comecei uma vez a escrever um estatuto de igreja com a finalidade de abrir um cnpj de igreja similar ao da [S.I.C.K.](https://cnpj.biz/17843274000145).

Está perdido em algum disco rígido antigo com o backup da ikiwiki da igreja. Fisicamente localizado no meu quarto em algum lugar de Porto Alegre. (12 de novembro de 2019).
